### ISSUE TITLE
Photo from Quaxio.com

### ISSUE THREAD

**Issue by jmnijsse** [alokmenghrajani/alokmenghrajani.github.com#14]
Hi,

I found a photo of an Arduino+lcd screen at your blog-site.
I wrote a quote for our public report (for the parents of the students) of our school (www.calvijncollege.nl) and this photo gives an impression of what arduino is.
Is it allowed to use this photo in our report?

Regards,
Johan Nijsse
technical education assistant Physics
Calvijn College Goes (NL)

**Comment by alokmenghrajani** [comment]
Sure, you can use the photo as long as you indicate the source. Thank you for asking.

If you are talking about http://quaxio.com/arduino_gps/overview.jpg, the thing on the left is an Arduino, on the right is a GPS unit and on the bottom in a LCD screen. These three components are connected using a bread board (sometimes called a prototyping board), which is the white thing in the middle. The Arduino reads the signal from the GPS receiver and displays the decoded time/date on the LCD.

All of the above components (except for the GPS receiver) were part of an Arduino starter kit (~$100). I highly recommend children/teenagers who are interested in electronics and/or computer science to play around with such a kit. These kits are also popular with people doing art-related projects.
