### ISSUE TITLE
problem with GPS code

### ISSUE THREAD

**Issue by 62beetle** [alokmenghrajani/alokmenghrajani.github.com#15]
In your sketch you use "include<LiquidCrystal.h>",   "include<ctype.h>" and "include<string.h>" I cannot find these in any library and the program will not step past them.
     What am I doing wrong? Or where can I find a library with these items?  I have been struggling to build a auto-pilot for my fishing boat but cant get past this point in the program.
Jim,
Manitoba, Canada

**Comment by alokmenghrajani** [comment]
LiquidCrystal.h is part of Arduino's standard library (see http://www.arduino.cc/en/Reference/Libraries). string.h and ctype.h are part of the C standard library.

Maybe you aren't using a compatible board or your IDE is messed up?

**Comment by 62beetle** [comment]
Hi,
I am using an arduino Uno and a sainsmart mega, I have downloaded the
latest arduino update so I think the IDE is okay but have not been able to
get a standard library to show up up the menu with string and ctype, will
try again. Many Thanks.
Jim

**Comment by 62beetle** [comment]
ok I now have string and ctype in the library, now it reports "stray '#' in
program" ???

**Comment by 62beetle** [comment]
forgot to add this error listI  and your gps code

On Sat, May 23, 2015 at 3:11 PM, Alok Menghrajani <notifications@github.com>
wrote:

> LiquidCrystal.h is part of Arduino's standard library (see
> http://www.arduino.cc/en/Reference/Libraries). string.h and ctype.h are
> part of the C standard library.
>
> Maybe you aren't using a compatible board or your IDE is messed up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alokmenghrajani/alokmenghrajani.github.com/issues/15#issuecomment-104940534>
> .
>



may22_GPS_w_errors:6: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:20: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:22: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:23: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:24: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:25: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:26: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:27: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:28: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:29: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:42: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:47: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:52: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:53: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:54: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:55: error: expected unqualified-id before numeric constant
may22_GPS_w_errors:58: error: expected unqualified-id before numeric constant
expected unqualified-id before numeric constant


1. /**
2. * Code to display the time & date from a GPS receiver on a LCD.
3. *
4. * This code was inspired by http://arduino.cc/en/Tutorial/LiquidCrystal and
5. * http://playground.arduino.cc/Tutorials/GPS
6. *
7. * For more information, see http://quaxio.com/arduino_gps/
8. */
9.
10. #include <LiquidCrystal.h>
11. #include <string.h>
12. #include <ctype.h>
13.
14. LiquidCrystal lcd(12, 11, 5, 4, 3, 2);
15.
16. int rxPin = 0; // RX pin
17. int txPin = 1; // TX pin
18. int byteGPS=-1;
19. char cmd[7] = "$GPRMC";
20. int counter1 = 0; // counts how many bytes were received (max 300)
21. int counter2 = 0; // counts how many commas were seen
22. int offsets[13];
23. char buf[300] = "";
24.
25. /**
26. * Setup display and gps
27. */
28. void setup() {
29. pinMode(rxPin, INPUT);
30. pinMode(txPin, OUTPUT);
31. Serial.begin(4800);
32. lcd.begin(16, 2);
33. lcd.print("waiting for gps");
34. offsets[0] = 0;
35. reset();
36. }
37.
38. void reset() {
39. counter1 = 0;
40. counter2 = 0;
41. }
42.
43. int get_size(int offset) {
44. return offsets[offset+1] - offsets[offset] - 1;
45. }
46.
47. int handle_byte(int byteGPS) {
48. buf[counter1] = byteGPS;
49. Serial.print((char)byteGPS);
50. counter1++;
51. if (counter1 == 300) {
52. return 0;
53. }
54. if (byteGPS == ',') {
55. counter2++;
56. offsets[counter2] = counter1;
57. if (counter2 == 13) {
58. return 0;
59. }
60. }
61. if (byteGPS == '*') {
62. offsets[12] = counter1;
63. }
64.
65. // Check if we got a <LF>, which indicates the end of line
66. if (byteGPS == 10) {
67. // Check that we got 12 pieces, and that the first piece is 6 characters
68. if (counter2 != 12 || (get_size(0) != 6)) {
69. return 0;
70. }
71.
72. // Check that we received $GPRMC
73. for (int j=0; j<6; j++) {
74. if (buf[j] != cmd[j]) {
75. return 0;
76. }
77. }
78.
79. // Check that time is well formed
80. if (get_size(1) != 10) {
81. return 0;
82. }
83.
84. // Check that date is well formed
85. if (get_size(9) != 6) {
86. return 0;
87. }
88.
89. // TODO: compute and validate checksum
90.
91. // TODO: handle timezone offset
92.
93. // print time
94. lcd.clear();
95. for (int j=0; j<6; j++) {
96. lcd.print(buf[offsets[1]+j]);
97. if (j==1) {
98. lcd.print("h");
99. } else if (j==3) {
100. lcd.print("m");
101. } else if (j==5) {
102. lcd.print("s UTC");
103. }
104. }
105.
106. // print date
107. lcd.setCursor(0, 1);
Back to top ?
108. for (int j=0; j<6; j++) {
109. lcd.print(buf[offsets[9]+j]);
110. if (j==1 || j==3) {
111. lcd.print(".");
112. }
113. }
114. return 0;
115. }
116. return 1;
117. }
118.
119. /**
120. * Main loop
121. */
122. void loop() {
123. byteGPS=Serial.read(); // Read a byte of the serial port
124. if (byteGPS == -1) { // See if the port is empty yet
125. delay(100);
126. } else {
127. if (!handle_byte(byteGPS)) {
128. reset();
129. }
130. }
131. }

**Comment by 62beetle** [comment]
Alok,
Did you get my updated problem with program etc?
Still won't run...
Jim

**Comment by alokmenghrajani** [comment]
Can you get Arduino's sample code running? E.g. the sample code which blinks a led on the board?

**Comment by 62beetle** [comment]
yes I can run blink and also "Hello world"

**Comment by alokmenghrajani** [comment]
What about http://www.arduino.cc/en/Tutorial/LiquidCrystal?

**Comment by fixme89** [comment]
What is this? Why's it on my device?
