### ISSUE TITLE
The "Contact Me" links don't include a #hash.

### ISSUE THREAD

**Issue by jwatte-imvu** [alokmenghrajani/alokmenghrajani.github.com#16]
contact_me.html references "hash" which is an empty value.
The URL in the address bar has an empty hash, and location.hash is empty in JavaScript console.
So ... crackme not working ;-)

**Comment by alokmenghrajani** [comment]
you aren't good with crackme's, are you?

**Comment by alokmenghrajani** [comment]
(hint: go visit http://foo.com/blah#1234 and look at what happens to location in your browser console/debugger).

**Comment by jwatte-imvu** [comment]
Oh, you want me to reverse derive the hash that would make a==b pass, not just patch the a==b test?
What I had to say wasn't important enough.

**Comment by alokmenghrajani** [comment]
Oh well. You can always post here.

**Comment by fixme89** [comment]
No unfortunately. Any help to fix the security of my device muchly appreciated
