### ISSUE TITLE
Sanitizer article img tag issue

### ISSUE THREAD

**Issue by bengotow** [alokmenghrajani/alokmenghrajani.github.com#18]
Hey! Was looking for exactly what you wrote up in your HTML sanitizer article for the Mailspring email client. (Long story short, we use `html-sanitizer` but it's slow and uses a pretty enormous 400kb HTML parser library, which is silly since we're an Electron app and have Chrome APIs. The HTML sanitizer also has odd bugs which occasionally cause emails to render wrong).

Anyway—thanks for writing the article! I wanted to let you know that I've done some testing, and it's not /quite/ isolated from the DOM the way it's written. Because the code clones existing nodes and creates new clean ones, it occasionally does this and requests the images present in the HTML:

```
const newNode = document.createElement('img');
newNode.setAttribute('src', 'http://...');
```

Unfortunately just this is enough to load that image src (you can paste those two lines into the browser console to try).

I'm not sure this is a problem, but it might be worth mentioning in the article because it's really subtle. For us, it's a big issue because we sanitize the HTML and then process it down even further to remove tracking pixels, etc. The only workaround I've found is to re-write the sanitizer to strip unwanted attributes / info rather than re-creating clean elements one attribute at a time.

https://github.com/alokmenghrajani/alokmenghrajani.github.com/blob/571b122870132697972387e9c81f8742561cf9dd/_posts/2015/2015-10-11-html_white_listed_sanitizer.html#L226

**Comment by alokmenghrajani** [comment]
I have no idea what issue you are running into. The following works fine for me. Open about:blank and type this in the console:
`var i = document.createElement('img'); i.setAttribute('src', 'https://quaxio.com/alok.jpg'); document.append(img)`

**Comment by alokmenghrajani** [comment]
You can also write a url sanitizer which will only allow a subset of images (e.g. only specific domains, or inline images, etc.). Keep in mind that if you want to disallow all images, you'll have to watch out for things like embedded style attributes with background-images.

I'll keep this issue open for a few days in case you want to add any additional info?

**Comment by alokmenghrajani** [comment]
> For us, it's a big issue because we sanitize the HTML and then process it down even further to remove tracking pixels, etc.

Perhaps that's your core issue. You should probably do all the processing as the parser walks through the DOM.

**Comment by bengotow** [comment]
Hey! Thanks for digging in to this — your example (opening `about:blank` and running those lines) also works for me. However, in the example source, `document.createElement` refers to the primary `window.document` not to the detached `doc` document you create in the setup function, so it's equivalent to running those commands in the console of a regular browser window which, at least for me, attempts to load the image.

I think a simple fix would be to use the new detached document created on line 196 (https://github.com/alokmenghrajani/alokmenghrajani.github.com/blob/571b122870132697972387e9c81f8742561cf9dd/_posts/2015/2015-10-11-html_white_listed_sanitizer.html#L196) when calling `document.createElement` instead of the document bound to the DOM?

Will definitely investigate refactoring our pipeline a bit more to do these things all at the same time, but it's a bit tricky because separate the app is broken into plugins that aren't coupled to each other much. Thanks!

**Comment by alokmenghrajani** [comment]
You are right, `document.implementation` doesn't trigger the side effect for img.src! I'll update the post.

Thanks a lot!
